[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stream_vault = "Cp34F2Ho7oCetL6UkfFDLyGfvh5FcPuRiT1DSHiEAVbF"
vault = "3X4cA5KNBo6yYw2aLwRgVPaX3RshUR62Y2Bo8GyXzYWg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts' --exclude 'tests/utils/**'"
